from pydantic import BaseModel, Field
from google import genai
from google.genai import types

from app.config import settings
from app.services.job_parser import parse_job_description


class ResumeTailoring(BaseModel):
    tailored_summary: str = Field(
        description=(
            "A concise, professional resume summary tailored to the "
            "target job. Use only information supported by the candidate "
            "profile and resume data."
        )
    )

    tailored_experience: str = Field(
        description=(
            "A professionally rewritten version of the candidate's "
            "experience. Preserve the candidate's actual experience and "
            "do not invent companies, responsibilities, technologies, "
            "achievements, metrics, or projects."
        )
    )

    tailoring_notes: list[str] = Field(
        description=(
            "Short explanations of how the resume was tailored for "
            "the target job."
        )
    )


client = genai.Client(
    api_key=settings.GEMINI_API_KEY
)


def _normalize_skill(skill: str) -> str:
    """Normalize skill names for reliable comparison."""
    return (
        skill.strip()
        .lower()
        .replace(".", "")
        .replace("-", "")
        .replace("_", "")
        .replace(" ", "")
    )


def calculate_skill_alignment(
    candidate_skills: list[str],
    required_skills: list[str],
    preferred_skills: list[str],
) -> dict:
    """
    Calculate ATS-style skill alignment using deterministic code.

    The score is NOT generated by the LLM.
    """

    candidate_map = {
        _normalize_skill(skill): skill
        for skill in candidate_skills
    }

    required_matches = []
    required_gaps = []

    for skill in required_skills:
        normalized = _normalize_skill(skill)

        if normalized in candidate_map:
            required_matches.append(skill)
        else:
            required_gaps.append(skill)

    preferred_matches = []

    for skill in preferred_skills:
        normalized = _normalize_skill(skill)

        if normalized in candidate_map:
            preferred_matches.append(skill)

    if required_skills:
        required_score = (
            len(required_matches) / len(required_skills)
        ) * 100
    else:
        required_score = 100.0

    if preferred_skills:
        preferred_score = (
            len(preferred_matches) / len(preferred_skills)
        ) * 100
    else:
        preferred_score = 100.0

    # Required skills carry more weight than preferred skills.
    ats_score = (
        required_score * 0.75
        + preferred_score * 0.25
    )

    return {
        "ats_score": round(ats_score, 2),
        "required_matches": required_matches,
        "required_gaps": required_gaps,
        "preferred_matches": preferred_matches,
        "required_score": round(required_score, 2),
        "preferred_score": round(preferred_score, 2),
    }


def tailor_resume(
    name: str,
    job_title: str,
    job_description: str,
    education: str,
    experience: str,
    candidate_skills: list[str],
) -> dict:
    """
    Tailor a candidate's resume for a specific job.

    Flow:
        Job Description
             ↓
        Job Parser
             ↓
        Skill Alignment
             ↓
        Gemini Resume Tailoring
             ↓
        Structured Result
    """

    # ---------------------------------------------------------
    # 1. Parse the job description using the existing parser
    # ---------------------------------------------------------

    job_analysis = parse_job_description(
        description=job_description,
        title=job_title,
    )

    # ---------------------------------------------------------
    # 2. Calculate skill alignment deterministically
    # ---------------------------------------------------------

    skill_alignment = calculate_skill_alignment(
        candidate_skills=candidate_skills,
        required_skills=job_analysis.required_skills,
        preferred_skills=job_analysis.preferred_skills,
    )

    # ---------------------------------------------------------
    # 3. Ask Gemini to tailor only the written content
    # ---------------------------------------------------------

    prompt = f"""
You are an expert resume tailoring system.

Your task is to tailor an existing candidate resume for a
specific job without inventing information.

TARGET JOB
----------
Title:
{job_title}

Job Description:
{job_description}

Extracted Required Skills:
{job_analysis.required_skills}

Extracted Preferred Skills:
{job_analysis.preferred_skills}

Extracted Experience Requirement:
{job_analysis.experience}

Extracted Education Requirement:
{job_analysis.education}


CANDIDATE
---------
Name:
{name}

Education:
{education}

Skills:
{candidate_skills}

Existing Experience:
{experience}


IMPORTANT RULES
---------------

1. NEVER invent experience.

2. NEVER invent:
   - companies
   - internships
   - projects
   - technologies
   - responsibilities
   - achievements
   - numbers
   - metrics
   - certifications

3. Only rewrite or reorganize information already provided
   by the candidate.

4. Make the summary relevant to the target job.

5. Naturally emphasize skills that the candidate actually has
   and that are relevant to the job.

6. Do not add a skill merely because it appears in the job
   description.

7. Do not claim that the candidate has a missing skill.

8. Keep the writing professional and concise.

9. Use ATS-friendly terminology when the candidate genuinely
   has the corresponding skill or experience.

10. If the candidate does not have enough experience to support
    a stronger statement, keep the statement conservative.

11. Tailoring should improve relevance, not change the truth
    of the candidate's background.

Return the result according to the provided schema.
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=ResumeTailoring,
        ),
    )

    if response.parsed is None:
        raise ValueError(
            "Gemini returned an invalid resume tailoring response."
        )

    tailored = response.parsed

    # ---------------------------------------------------------
    # 4. Return AI content + deterministic ATS analysis
    # ---------------------------------------------------------

    return {
        "job_title": job_title,
        "job_analysis": {
            "role": job_analysis.role,
            "required_skills": job_analysis.required_skills,
            "preferred_skills": job_analysis.preferred_skills,
            "experience": job_analysis.experience,
            "education": job_analysis.education,
        },
        "tailored_summary": tailored.tailored_summary,
        "tailored_experience": tailored.tailored_experience,
        "tailoring_notes": tailored.tailoring_notes,
        "ats_analysis": skill_alignment,
    }